---
- name: Configure the k3s service
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: '0755'
  when: ansible_host in hostvars[groups['worker']]['ansible_host'] | default(groups['worker'])

- name: Manage k3s service
  ansible.builtin.systemd:
    name: k3s-node
    daemon_reload: true
    state: restarted
    enabled: true
  when: ansible_host in hostvars[groups['worker']]['ansible_host'] | default(groups['worker'])
